services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: airbnb_DWH

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"

    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

    networks:
      - data_pipeline_network

volumes:
  sqlserver_data:

networks:
  data_pipeline_network:
    driver: bridge